# file: "scripts/mongo/mongodb_stack_for_test.yml"
# 2022-03-18 | CR

# Use http://localhost:8081 to access the MongoDb Admin UI.
# Use user: "admin" and password: "pass" as credentials to access the Admin UI.
# Use "mongodb://root:example@mongo:27017/" as URL to connect to the local MongoDb database.
version: '3.1'

services:

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    expose:
      - 27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
