# secure_local_server/Dockerfile
# 2024-04-10 | CR

# Use an official Python 3.xx slim image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Expose the port the app runs on (if needed)
EXPOSE 8000
