# Use an official Python 3.xx slim image
# FROM python:3.10-slim
FROM python:3.13.5-slim

# Set the working directory in the container
WORKDIR /app

# Expose the port the app runs on (if needed)
EXPOSE 8000
